site:
  title: Open Beat Control User Guide
  url: https://obc-guide.deepsymmetry.org/
  start_page: open-beat-control::README.adoc
content:
  sources:
  - url: ./..
    branches: HEAD
    start_path: doc
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
ui:
  bundle:
    url: https://deepsymmetry.org/media/antora/ui-bundle-3.zip
    snapshot: true
