= Messages
James Elliott <james@deepsymmetry.org>
:icons: font
:experimental:
:guide-top: README

// Set up support for relative links on GitHub, and give it
// usable icons for admonitions, w00t! Add more conditions
// if you need to support other environments and extensions.
ifdef::env-github[]
:outfilesuffix: .adoc
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::env-github[]

// Render section header anchors in a GitHub-compatible way.
ifndef::env-github[]
:idprefix:
:idseparator: -
endif::env-github[]

This page lists the OSC messages that you can send to Open Beat
Control, and the responses (if any) that they will produce. Each
message is identified by its OSC path.

[[beats]]
== /beats

Tells Open Beat Control to report any Beat messages that are seen on
the DJ Link network. This allows you to align performances at the beat
and bar level.

=== Arguments

[cols="1m,1m,2,5",options="header",]
|=======================================================================

|Name |Type |Default |Purpose
|command |string |_n/a_ |The action you want to take, see below.

|port |integer |The response port |If you want responses to go to a different port than normal, you can supply that port number here.

|=======================================================================

The command you send as the first argument determines whether beat
reporting is turned on or off. The port number to which the beat
messages are sent will be the default response port unless you supply
a second argument, in which case they will be sent to that port.

==== Commands

`stream`:: Tells Open Beat Control to report beat packets as OSC
`/beat` messages, to the specified port if you supply one, or to the
default response port. You can have more than one stream running at
the same time if you use different port numbers to set them up.

`stop`:: Stops reporting beat packets over OSC. You must specify the
same port number (or lack of one) as you used when setting up the
stream.

==== Examples

* `/beats stream` (Beat packets will be reported on the default
  response port)
* `/beats stream 2000` (Beat packets will be reported on port 2000)
* `/beats stop` (stops reporting Beat packets on the default response
  port)
* `/logging stop 2000` (stops reporting Beat packets on port 2000)


=== Responses

`/beat`:: Sent for each Beat packet seen while the stream is active. Each `/beat` message has five arguments:

==== `/beat` Arguments

[cols="2m,1m,6",options="header",]
|=======================================================================
|Name |Type |Meaning
|device |int |The player number that send the beat. Mixers use number 33.
|beat |int |Position within measure, 1--4. Not meaningful from mixers.
|tempo |float |Beats per minute being played.
|track-tempo |float |Beats per minute of track at normal speed.
|pitch |float |Speed at which track is being played, 1.0 means normal, 0.5 means half speed, etc.
|=======================================================================

==== Examples

* `/beat 2 4 131.603973 132. 0.997`

Here, player 2 just started playing the final (fourth) beat of a bar,
at 131.6 BPM. The natural track tempo at this point is 132 BPM, and it
is playing at 99.7% normal speed.



[[devices]]
== /devices

Find out what Pro DJ Link devices are visible on the network, either
now or (by setting up a stream) as they come and go.

=== Arguments

[cols="1m,1m,2,5",options="header",]
|=======================================================================

|Name |Type |Default |Purpose
|command |string |_n/a_ |The action you want to take, see below.

|port |integer |The response port |If you want responses to go to a different port than normal, you can supply that port number here.

|=======================================================================

The behavior of this message is controlled by the value you send as
the first argument. The port number to which the response is sent will
be the default response port unless you supply a second argument, in
which case the response will be sent to that port.

==== Commands

`list`:: Sends responses describing all devices currently on the
network.

`stream`:: Starts out just like the `list` command, but will also send
responses any time a new device is seen on the network, or if an
existing device disappears, until you send a `stop` command. You can
have more than one stream running at the same time if you use
different port numbers to set them up.

`stop`:: Stops sending messages as devices are found or lost. You must
specify the same port number (or lack of one) as you used when setting
up the stream.

==== Examples

* `/devices list` (sends current devices to default response port)
* `/devices list 4000` (sends current devices to port 4000)
* `/devices stream` (sends current devices to default response port,
  and any device changes that happen in the future will be sent there
  as well)
* `/devices stream 4200` (sends current devices to port 4200, and any
  device changes that happen in the future will be sent there as well)
* `/devices stop` (stops sending device changes to the default
  response port)
* `/devices stop 4200` (stops sending device changes to port 4200)


=== Responses

`/device/found`:: Sent for each device that is on the network (and,
for streams, for each new device that appears). The arguments are the
device (player) number, its name, and its IP address.

`/device/lost`:: Sent for streams whenever a device has disappeared
from the network. The arguments are the device (player) number, its
name, and its IP address.

==== Examples

* `/device/found 2 CDJ-2000 172.30.20.5`
* `/device/lost 33 DJM-2000 172.30.20.4`

[[log]]
== /log

As described in the <<Communicating#sending,Communicating>> section,
the `/log` message tells Open Beat Control to output the message to
the log file, or if no log file has been configured, to the console.

=== Arguments

_Anything at all_

Upon receipt of this message, Open Beat Control will log all the
details it knows about the message it received, including the types
and values of the arguments, and the host and port from which it was
received, to the console or log file.

=== Responses

_None_

[[logging]]
== /logging

Tells Open Beat Control to forward any log messages via OSC as well as
writing them to its log file. This can be convenient if you are
running OBC on another machine, and can more conveniently log the
information from this one.

=== Arguments

[cols="1m,1m,2,5",options="header",]
|=======================================================================

|Name |Type |Default |Purpose
|command |string |_n/a_ |The action you want to take, see below.

|port |integer |The response port |If you want responses to go to a different port than normal, you can supply that port number here.

|=======================================================================

The command you send as the first argument determines whether log
forwarding is turned on or off. The port number to which the log
messages are sent will be the default response port unless you supply
a second argument, in which case they will be sent to that port.

==== Commands

`stream`:: Tells Open Beat Control to send any future log messages as
OSC messages, to the specified port if you supply one, or to the
default response port. You can have more than one stream running at
the same time if you use different port numbers to set them up.

`stop`:: Stops sending log messages over OSC. You must specify the
same port number (or lack of one) as you used when setting up the
stream.

==== Examples

* `/logging stream` (future log messages will be sent to the default
  response port)
* `/logging stream 1492` (future log messages will be sent to port
  1492)
* `/logging stop` (stops sending log messages to the default response
  port)
* `/logging stop 1492` (stops sending log messages to port 1492)


=== Responses

`/log`:: Sent for each entry made to the Open Beat Control log file
while the stream is active.

==== Examples

* `/log 2019-Oct-31 23:50:42 INFO [open-beat-control.core:222] - Virtual CDJ running as Player 5`


[[respond]]
== /respond

As described in the <<Communicating#response-port,Communicating>>
section, the `/respond` message tells Open Beat Control the port
number it should use to send OSC responses back to your own software.

=== Arguments

[cols="1,1,1,4",options="header",]
|=======================================================================

|Name |Type |Default |Purpose
|`port` |`integer` |_see below_ |The port number to which response messages will be sent.

|=======================================================================

If you do not supply an argument to the `/respond` command, it
removes any response port setting that you had previously established,
so Open Beat Control will revert to its default behavior of sending
responses to a port that is numbered one higher than the port from
which incoming messages are being received.

==== Examples

* `/respond 5000` (responses will be sent to port 5000)
* `/respond`  (responses will be sent to the default port)

=== Responses

_None_

== Learning More

****

* Continue to <<{guide-top}#what-next,What Next?>>
* Return to <<{guide-top}#open-beat-control-user-guide,Top>>

****

include::partial$Footer.adoc[]
