= Messages
James Elliott <james@deepsymmetry.org>
:icons: font
:experimental:
:guide-top: README

// Set up support for relative links on GitHub, and give it
// usable icons for admonitions, w00t! Add more conditions
// if you need to support other environments and extensions.
ifdef::env-github[]
:outfilesuffix: .adoc
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::env-github[]

// Render section header anchors in a GitHub-compatible way.
ifndef::env-github[]
:idprefix:
:idseparator: -
endif::env-github[]

This page lists the OSC messages that you can send to Open Beat
Control, and the responses (if any) that they will produce. Each
message is identified by its OSC path.

[[beats]]
== `/beats`

Tells Open Beat Control to report any Beat messages that are seen on
the DJ Link network. This allows you to align performances at the beat
and bar level.

:omit-argument-descriptions:
include::partial$stream_arguments.adoc[]

The command you send as the first argument determines whether beat
reporting is turned on or off. The port number to which the beat
messages are sent will be the default response port unless you supply
a second argument, in which case they will be sent to that port.

==== Commands

`stream`:: Tells Open Beat Control to report beat packets as OSC
`/beat` messages, to the specified port if you supply one, or to the
default response port. You can have more than one stream running at
the same time if you use different port numbers to set them up.

`stop`:: Stops reporting beat packets over OSC. You must specify the
same port number (or lack of one) as you used when setting up the
stream.

==== Examples

* `/beats stream` (Beat packets will be reported on the default
  response port)
* `/beats stream 2000` (Beat packets will be reported on port 2000)
* `/beats stop` (stops reporting Beat packets on the default response
  port)
* `/beats stop 2000` (stops reporting Beat packets on port 2000)

=== Responses

`/beat`::
Sent for each Beat packet seen while the stream is active. Each `/beat` message has five arguments:
+
[cols="2m,1m,6",options="header",]
|=======================================================================
|Name |Type |Meaning
|device |int |The player number that sent the beat. Mixers use number 33.
|beat |int |Position within measure, 1--4. Not meaningful from mixers.
|tempo |float |Beats per minute being played.
|track-tempo |float |Beats per minute of the track at normal speed.
|pitch |float |Speed at which track is being played, 1.0 means normal, 0.5 means half speed, etc.
|=======================================================================

NOTE: Beats from the mixer always report a pitch of `1.0`, so
`track-tempo` is the same as `tempo` (which makes sense, since they
don't have any actual track to play).

==== Examples

* `/beat 2 4 131.603973 132. 0.997`
+
Here, player 2 just started playing the final (fourth) beat of a bar,
at 131.6 BPM. The natural track tempo at this point is 132 BPM, and it
is playing at 99.7% normal speed.


[[cued]]
== `/cued`

Find out the cued states of Pro DJ Link devices on the network, either
now or (by setting up a stream) as they change. Players report they
are cued when they are positioned at the currently active cue point.
Only players that are cued can be told to start playing using the
<<fader-start,`/fader-start` message>>.

include::partial$stream_arguments.adoc[]

:stream-type: cued state
:stream-command: /cued
:stream-port: 4210
include::partial$stream_commands.adoc[]

=== Responses

``/cued/``\{device}:: Sent for each device whose cued state is known
(and, for streams, for each cued state change for that device). The
value of _\{device}_ will be the device number (1 through 4), and the
message's argument is `0` if the device is not cued (not currently
positioned at the active cue point), and `1` if it is cued (positioned
at the current cue point).

* `/cued/2 1`
* `/cued/3 0`


[[devices]]
== `/devices`

Find out what Pro DJ Link devices are visible on the network, either
now or (by setting up a stream) as they come and go.

include::partial$stream_arguments.adoc[]

:stream-type: device
:stream-command: /devices
:stream-port: 4000
include::partial$stream_commands.adoc[]


=== Responses

`/device/found`:: Sent for each device that is on the network (and,
for streams, for each new device that appears). The arguments are the
device (player) number, its name, and its IP address.

`/device/lost`:: Sent for streams whenever a device has disappeared
from the network. The arguments are the device (player) number, its
name, and its IP address.

==== Examples

* `/device/found 2 CDJ-2000 172.30.20.5`
* `/device/lost 33 DJM-2000 172.30.20.4`


[[load]]
== `/load`

Send a message telling a player to load a track.

=== Arguments

[cols="2m,1m,6",options="header",]
|=======================================================================

|Name |Type |Purpose
|target-player |integer |The device number of the player you want to load a track on.

|source-device |integer |The device number of the player, rekordbox laptop, rekordbox mobile device from which the track can be loaded.

|slot |string |The slot from which the track should be loaded, one of `cd`, `sd`, `usb`, or `collection` (if a rekordbox laptop/mobile device).

|track-type |string |The kind of track being loaded, one of `cd`, `rekordbox`, or `unanalyzed` (digital audio not indexed by rekordbox).

|id |integer |The rekordbox (or other) id of the track to be loaded.

|=======================================================================

NOTE: Most players we have encountered are able to load tracks of type
`rekordbox` using this mechanism, because it was designed to support a
feature in the rekordbox application. I would not expect loading
tracks from the `cd` slot or `unanalyzed` tracks to work.

==== Examples

* `/load 2 3 usb rekordbox 819` (ask player 2 to load a track from
  player 3's USB slot, which holds a rekordbox export, and the desired
  track has rekordbox ID 819)
* `/load 3 17 collection rekordbox 2739` (ask player 3 to load a track
  from rekordbox laptop #1's linked collection, and the desired track
  has rekordbox ID 2739)

=== Responses

If there is a problem sending the message, an `/error` message on the
configured (or default) response port will describe it. Otherwise, if
you have a <<loaded,`/loaded` stream>> active, once the track loads it
will be reported to that stream.


[[loaded]]
== `/loaded`

Find out about the tracks loaded by Pro DJ Link players on the
network, either now or (by setting up a stream) as they change.

include::partial$stream_arguments.adoc[]

:stream-type: track load state
:stream-command: /loaded
:stream-port: 5432
include::partial$stream_commands.adoc[]

=== Responses

``/loaded/``\{device}:: Sent for each device whose track load state is
known (and, for streams, for each track load state change for that
device). The value of _\{device}_ will be the device number (1 through
4), and the message's argument is made up of four values:

* The device number from which the track was loaded, or `0` if there
  is no track loaded. This will be `1` through `4` for a normal
  player, or `17` or `18` if the track was loaded from a rekordbox
  laptop or mobile phone.
* The slot from which the track was loaded, one of `none`, `cd`, `sd`,
  `usb`, `collection` (from rekordbox), or `unknown`.
* The type of the track, one of `none`, `cd`, `rekordbox`,
  `unanalyzed` (digital audio file not indexed by rekordbox), or
  `unknown`.
* The ID of the track, which is either the rekordbox ID, or the track
  number (for an audio CD), or the file ID (for an unanalyzed track).

==== Examples

* `/loaded/1 0 none none 0`
* `/loaded/2 3 usb rekordbox 820`
* `/loaded/3 17 collection rekordbox 1995`
* `/loaded/4 4 cd cd 2`

NOTE: You can cause players to load rekordbox tracks using the
<<load,`/load` message>>.


[[fader-start]]
== `/fader-start`

Uses the Fader Start mechanism to tell some players to start or stop
playing. (They will only start if they are paused at the current cue
point.)

TIP: You can determine which players positioned at their cue points
using the <<cued,`/cued` stream>>. This will let you know if
`/fader-start` will be able to start them playing.

=== Arguments

You can supply one or more device numbers as arguments. If those
numbers are positive, that player will be told to start playing. If
any number is negative, it will be converted to a postive number and
that player will be told to stop.

==== Examples

* `/fader-start 1 -2` (try to start player 1, and stop player 2)

=== Responses

If there is a problem sending the message, an `/error` message on the
configured (or default) response port will describe it. Otherwise, if
you have a <<playing,`/playing` stream>> active, any playing state
changes will be reported to that stream.


[[log]]
== `/log`

As described in the <<Communicating#sending,Communicating>> section,
the `/log` message tells Open Beat Control to output the message to
the log file, or if no log file has been configured, to the console.

=== Arguments

_Anything at all_

Upon receipt of this message, Open Beat Control will log all the
details it knows about the message it received, including the types
and values of the arguments, and the host and port from which it was
received, to the console or log file.

=== Responses

_None_

[[logging]]
== `/logging`

Tells Open Beat Control to forward any log messages via OSC as well as
writing them to its log file. This can be convenient if you are
running OBC on another machine, and can more conveniently log the
information from this one.

=== Arguments

[cols="1m,1m,2,5",options="header",]
|=======================================================================

|Name |Type |Default |Purpose
|command |string |_n/a_ |The action you want to take, see below.

|port |integer |The response port |If you want responses to go to a different port than normal, you can supply that port number here.

|=======================================================================

The command you send as the first argument determines whether log
forwarding is turned on or off. The port number to which the log
messages are sent will be the default response port unless you supply
a second argument, in which case they will be sent to that port.

==== Commands

`stream`:: Tells Open Beat Control to send any future log messages as
OSC messages, to the specified port if you supply one, or to the
default response port. You can have more than one stream running at
the same time if you use different port numbers to set them up.

`stop`:: Stops sending log messages over OSC. You must specify the
same port number (or lack of one) as you used when setting up the
stream.

==== Examples

* `/logging stream` (future log messages will be sent to the default
  response port)
* `/logging stream 1492` (future log messages will be sent to port
  1492)
* `/logging stop` (stops sending log messages to the default response
  port)
* `/logging stop 1492` (stops sending log messages to port 1492)


=== Responses

`/log`:: Sent for each entry made to the Open Beat Control log file
while the stream is active.

==== Examples

* `/log 2019-Oct-31 23:50:42 INFO [open-beat-control.core:222] - Virtual CDJ running as Player 5`


[[master]]
== `/master`

Allows you to receive OSC messages when new players become Tempo
Master, or when the current Tempo Master starts playing a new beat, or
changes tempo. Also enables you to tell a specific player to become
Tempo Master.

=== Arguments

[cols="1,1m,2,5",options="header",]
|=======================================================================

|Name |Type |Default |Purpose
|`command` |string |_n/a_ |The action you want to take, see below.

|`port` or `player` |integer |The response port or _n/a_ |For `stream` and `stop`, if you want responses to go to a different port than normal, you can supply that port number here. For `appoint` you must supply the player you want to become the new Master.

|=======================================================================

The command you send as the first argument determines the meaning of
the second. As with other streamable commands, the `list` command
reports the current state of the Tempo Master, while the `stream` and
`stop` commands control whether Tempo Master reporting is turned on or
off; the port number to which the Tempo Master messages are sent will
be the default response port unless you supply a second argument,
`port`, in which case they will be sent to that port.

The `appoint` command tells a player to become Tempo Master, and
requires a `player` argument identifying the player number you want to
appoint as Master.

:stream-type: Tempo Master state
:stream-omit-examples:
include::partial$stream_commands.adoc[]
`appoint`:: Causes Open Beat Control to send a message to the player
whose number you supply as a second argument, telling it to become the
new Tempo Master if it can.

:stream-type: Tempo Master state
:stream-command: /master
:stream-port: 2010
include::partial$stream_examples.adoc[]
* `/master appoint 2` (tells Player 2 to become Tempo Master)

=== Responses

`/master/beat`:: Sent for each Beat packet seen from the Tempo Master
while the stream is active. Each `/master/beat` message has five
arguments:
+
[cols="2m,1m,6",options="header",]
|=======================================================================
|Name |Type |Meaning
|device |int |The player number that sent the beat. Mixers use number 33.
|beat |int |Position within measure, 1--4. Not meaningful from mixers.
|tempo |float |Beats per minute being played.
|track-tempo |float |Beats per minute of the track at normal speed.
|pitch |float |Speed at which track is being played, 1.0 means normal, 0.5 means half speed, etc.
|=======================================================================
+
NOTE: Beats from the mixer always report a pitch of `1.0`, so
`track-tempo` is the same as `tempo` (which makes sense, since they
don't have any actual track to play).

`/master/tempo`:: Sent whenever the tempo reported by the Tempo Master
changes. Its single `float` argument is the new tempo.

`/master/playing`:: Sent whenever the tempo master is determined to
have started or stopped playing. Its single `int` argument will be `1`
if it is playing, and `0` if it is not. (Although this is slightly
redundant with the <<playing,`/playing` stream>>, it enables you to
easily create patches that depend on the presence of an active master
player, without having to separately track playing states and the
device number of the tempo master.)

`/master/player`:: Sent whenever a new player takes over as Tempo Master.
Its single `int` argument is the number of the new Master player.


`/master/none`:: Sent when the current Tempo Master resigns that role
(perhaps by disappearing from the network) without another being
appointed.

==== Examples

* `/master/beat 3 2 128. 128. 1.`
+
Here, Player 3 was the Tempo Master and just started playing the
second beat of a bar, at 128.0 BPM, which was the natural track tempo
at this point, so it is playing at 100% normal speed.
* `/master/tempo 128.1` (tempo has changed to 128.1 BPM)
* `/master/playing 1` (the Tempo Master has started playing a track)
* `/master/player 2` (player 2 has just become the new Tempo Master)
* `/master/none` (there is no longer a Tempo Master)


[[on-air]]
== `/on-air`

Find out the on-air states of Pro DJ Link devices on the network,
either now or (by setting up a stream) as they change.

include::partial$stream_arguments.adoc[]

:stream-type: on-air state
:stream-command: /on-air
:stream-port: 4001
include::partial$stream_commands.adoc[]

=== Responses

``/on-air/``\{device}:: Sent for each device whose on-air state is
known (and, for streams, for each on-air state change for that
device). The value of _\{device}_ will be the device number (1 through
4), and the message's argument is `0` if the device is off-air (not
audible), and `1` if it is on-air (connected to a mixer channel whose
output is currently audible).

NOTE: The on-air value of a device will only be meaningful if it is conneted
to a Nexus mixer and this feature is active. If there is no Nexus
mixer on the network, you can change players' on-air state using the
<<set-on-air,`/set-on-air` message>>. (If there is a Nexus mixer
present, it will reset the on-air states of the devices to what it
believes they should be a fraction of a second after they react to
your command.)

==== Examples

* `/on-air/1 0`
* `/on-air/2 1`


[[playing]]
== `/playing`

Find out the playing states of Pro DJ Link devices on the network,
either now or (by setting up a stream) as they change.

include::partial$stream_arguments.adoc[]

:stream-type: playing state
:stream-command: /playing
:stream-port: 4002
include::partial$stream_commands.adoc[]

=== Responses

``/playing/``\{device}:: Sent for each device whose playing state is
known (and, for streams, for each playing state change for that
device). The value of _\{device}_ will be the device number (1 through
4), and the message's argument is `0` if the device is stopped, and
`1` if it is playing.

==== Examples

* `/playing/2 1`
* `/playing/3 0`

NOTE: You can control players' playing state using the
<<fader-start,`/fader-start` message>>.


[[respond]]
== `/respond`

As described in the <<Communicating#response-port,Communicating>>
section, the `/respond` message tells Open Beat Control the port
number it should use to send OSC responses back to your own software.

=== Arguments

[cols="1,1,1,4",options="header",]
|=======================================================================

|Name |Type |Default |Purpose
|`port` |`integer` |_see below_ |The port number to which response messages will be sent.

|=======================================================================

If you do not supply an argument to the `/respond` command, it
removes any response port setting that you had previously established,
so Open Beat Control will revert to its default behavior of sending
responses to a port that is numbered one higher than the port from
which incoming messages are being received.

==== Examples

* `/respond 5000` (responses will be sent to port 5000)
* `/respond`  (responses will be sent to the default port)

=== Responses

_None_

[[set-on-air]]
== `/set-on-air`

Sends a message telling the CDJs which are on-air (that is, which are
connected to a mixer channel whose output is currently audible, given
the positions of the channel faders and cross-fader).

If there is an actual Nexus mixer on the network, this is not a very
useful message, because within a fraction of a second of the players
responding to it, the mixer will send out a new on-air message telling
the players the actual state of its faders. But if you are using
another kind of mixer that sends MIDI messages about its fader state,
you can translate those messages to on-air states of the players using
this message to achieve results like a Nexus mixer.

=== Arguments

With no arguments, all players are set to off-air. Supply the device
numbers of the players that are currently on-air as arguments, and
those players will be set on-air.

==== Examples

* `/set-on-air` (all players are off the air)
* `/set-on-air 1 3` (players 1 and 3 are on the air, 2 and 4 are off)

=== Responses

If there is a problem sending the message, an `/error` message on the
configured (or default) response port will describe it. Otherwise, if
you have an <<on-air,`/on-air` stream>> active, the on-air state
changes of the players will be reported on that stream.


[[set-sync]]
== `/set-sync`

Sends messages telling CDJs (or the mixer) to turn Sync mode on or off.

=== Arguments

You can supply one or more device numbers as arguments. If those
numbers are positive, that player (or the mixer, for device number 33)
will be told to enter Sync mode. If any number is negative, it will be
converted to a postive number and that device will be told to turn off
Sync.

==== Examples

* `/set-sync` 2 3 (put players 2 and 3 in Sync mode)
* `/set-sync 1 -4 33` (put player 1 and the mixer in Sync mode, and
  take player 4 out of Sync mode)

=== Responses

If there is a problem sending the message, an `/error` message on the
configured (or default) response port will describe it. Otherwise, if
you have a <<synced,`/synced` stream>> active, any sync state changes
will be reported to that stream.


[[synced]]
== `/synced`

Find out the sync states of Pro DJ Link devices on the network,
either now or (by setting up a stream) as they change.

include::partial$stream_arguments.adoc[]

:stream-type: sync state
:stream-command: /synced
:stream-port: 4003
include::partial$stream_commands.adoc[]

=== Responses

``/sync/``\{device}:: Sent for each device whose sync state is known
(and, for streams, for each playing state change for that device). The
value of _\{device}_ will be the device number (1 through 4 for CDJs,
33 for mixers), and the message's argument is `0` if the device is
unsynced, and `1` if it is in Sync mode.

==== Examples

* `/sync/4 0`
* `/sync/33 1`

NOTE: You can control players' sync state using the
<<set-sync,`/set-sync` message>>.


[[tempos]]
== `/tempos`

Find out the known tempos of Pro DJ Link devices on the network,
either now or (by setting up a stream) as they change.

include::partial$stream_arguments.adoc[]

:stream-type: tempo
:stream-command: /tempo
:stream-port: 4200
include::partial$stream_commands.adoc[]

=== Responses

``/tempo/``\{device}:: Sent for each device whose tempo is known (and,
for streams, for each tempo change for that device). The value of
_\{device}_ will be the device number (1 through 4 for CDJs, 33 for
mixers), and the message's argument is the current effective tempo of
that device.

==== Examples

* `/tempo/33 127.190002`
* `/tempo/2 127.190399`


== Learning More

****

* Continue to <<{guide-top}#what-next,What Next?>>
* Return to <<{guide-top}#open-beat-control-user-guide,Top>>

****

include::partial$Footer.adoc[]
